version: '3.10'

services:
  api:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
      target: pv
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/api
    command: "uvicorn backend.api:app --host 0.0.0.0 --port 8001 --reload"
    restart: always
    networks:
      - app
    container_name: fastapi 

  ui:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
      target: pv
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./frontend:/app 
    restart: always
    networks:
      - app 
    container_name: streamlit 

networks:
  app:
    driver: bridge
